name = "notice"
main = "src/index.ts"
compatibility_date = "2025-05-13"
compatibility_flags = ["nodejs_compat"]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
invocation_logs = true

[vars]
SUBSCRIPTION_PATH = [your_host_url]/worker

[[routes]]
pattern = [your_host_url]/worker
zone_id = [your_zone_id]

[triggers]
crons = ["* * * * *"]

kv_namespaces = [
  { binding = "Notice-Book", id = "your_kv_namespace_id" }
]
